### ISSUE TITLE
Style question

### ISSUE THREAD

**Issue by dhouck** [SabrinaJewson/sabrinajewson.github.io#3]
In your excellent error post, you say
> You might have noticed I put my imports on separate lines each at bottom — I do have my reasons for this, but that’s best saved for another day ;)

I am curious about this; since it looks like youʼre no longer updating the blog, do you have another resource that might explain this practice?  I havenʼt seen it as common in any language, I canʼt find other people mentioning it, and Iʼm only coming up with weak guesses myself.

**Comment by SabrinaJewson** [comment]
Hi, and sorry for the late response!

My reasoning for putting imports at the end is to follow the general consistent philosophy of “important stuff at the top, unimportant stuff at the bottom”: that is, when I open a file I want to first of all see the main thing the file does, keeping irrelevant helpers and utilities as low down as possible. So, if you have a file like this:

```rs
use some::function;

pub fn the_main_function() { /* business logic */ }

fn utility_function() {}
```

I find it inconsistent that the “reading order” goes the_main_function → utility_function → use, and putting imports at the bottom rectifies this. It would also be consistent to put imports at the top, then utility code, then main logic, more common in “single-pass” languages like C (which is why it makes sense to have #includes at the top in such languages), but I think since Rust can work with things in reverse order, it is overall more readable to use this style. I don’t feel incredibly strongly about this — I don’t mind working with other styles at all — it’s just something nice I like to use in my own code.

**Comment by dhouck** [comment]
Ah, that makes sense.  I have a lot of conflicting thoughts about how things should be ordered in files, but that does make sense especially with how you were ordering everything else.
